FROM python:2.7

# ARG UNAME=user
# ARG UID=1000
# ARG GID=1000

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


