version: '3.7'
x-build: &default-build
  context: ../
  args:
    - UID=1000
    - GID=1000
x-volumes: &default-volumes
  - '${HOME}:${HOME}'

services:
  dev:
    build: 
      << : *default-build
      dockerfile:  .devcontainer/Dockerfile
    image: foo.bar
    privileged: true
    volumes: *default-volumes
    working_dir: ${HOME}
    environment:
      - HOME=${HOME}